language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r REQUIREMENTS.txt
script:
  - [run]
      source =
      */.aviansoftwareminimumviableproduct/*
  - coverage run --source aviansoftwareminimumviableproduct -m unittest discover
after_success:
  - coveralls
