language: python
python:
  - "3.7"
os: windows
#dist: xenial
before_install:
      # configure a headless display
      - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
      - source ./gl-ci-helpers/travis/setup_headless_display.sh
install:
  - pip install -r REQUIREMENTS.txt
script:
  - coverage run --source=aviansoftwareminimumviableproduct -m unittest discover -s tests
after_success:
  - coveralls --service=travis-pro
