language: python
python:
  - "3.7"
os: linux

install:
  - pip install -r REQUIREMENTS.txt
script:
  - coverage run --source=aviansoftwareminimumviableproduct -m unittest discover -s tests
after_success:
  - coveralls --service=travis-pro
